services:

  db-credenciales:
    image: mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=rabano
      - MYSQL_PASSWORD=htmlcssjs
      - MYSQL_DATABASE=credenciales
    ports:
      - 3306:3306
    networks:
      - auth

  db-usuarios:
    image: mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=rabano
      - MYSQL_PASSWORD=htmlcssjs
      - MYSQL_DATABASE=usuarios
    ports:
      - 3307:3306
    networks:
      - auth

  db-ventas:
    image: mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=rabano
      - MYSQL_PASSWORD=htmlcssjs
      - MYSQL_DATABASE=ventas
    ports:
      - 3308:3306
    networks:
      - auth

  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_HOSTS=db-credenciales, db-usuarios, db-ventas
      - PMA_USER=rabano
      - PMA_PASSWORD=htmlcssjs
    networks:
      - auth

networks:
  auth:
    driver: bridge