spring:
  application:
    name: MicroservicioEureka

server:
  port: 8761

eureka:
  instance:
    hostname: 0.0.0.0
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://0.0.0.0:${server.port}/eureka/