server:
  port: 8080

spring:
  application:
    name: MicroservicioGateway


  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: http://127.0.0.1:8081
            predicates:
              - Path=/auth/**

    discovery:
      locator:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka


